apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.appname }}
  namespace: {{ .Values.argocd.namespace }}
spec:
  project: default
  destination:
    server: {{ .Values.cluster.address }}
    namespace: {{ .Values.cluster.namespace }}
  sources:
  - repoURL: {{ .Values.values.repo_URL }}
    targetRevision: {{ .Values.values.branch }}
    ref: values
  - repoURL: {{ .Values.postgresql.repo_URL }}
    targetRevision: {{ .Values.postgresql.targetRevision }}
    chart: {{ .Values.postgresql.chart_name }}
    helm:
      valueFiles:
        {{- range .Values.postgresql.valueFiles }}
        - $values/app-values/Postgresql/{{ . }}
        {{- end }}
      values: |
        fullnameOverride: {{ .Values.postgresql.fullnameOverride }}
  - repoURL: {{ .Values.keycloak.repo_URL }}
    targetRevision: {{ .Values.keycloak.targetRevision }}
    chart: {{ .Values.keycloak.chart_name }}
    helm:
      valueFiles:
        {{- range .Values.keycloak.valueFiles }}
        - $values/app-values/Keycloak/{{ . }}
        {{- end }}
      values: |
        fullnameOverride: {{ .Values.keycloak.fullnameOverride }}
        apiUrl: "https://authority.be.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}"
        extraEnvVars:
        - name: KC_HOSTNAME_ADMIN_URL
          value: "https://authority.be.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}/auth"
        - name: KC_HOSTNAME_URL
          value: "https://authority.be.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}/auth"
  - repoURL: {{ .Values.ejbca.repo_URL }}
    path: {{ .Values.ejbca.folder }}
    targetRevision: {{ .Values.ejbca.branch }}
    helm:
      valueFiles:
        {{- range .Values.ejbca.valueFiles }}
        - $values/app-values/ejbca/{{ . }}
        {{- end }}
      values: |
        fullnameOverride: {{ .Values.ejbca.fullnameOverride }}
        hostname: &hostname ejbca-community-helm.{{ .Values.cluster.namespace }}.svc.cluster.local
        ejbca:
          env:
            HTTPSERVER_HOSTNAME: *hostname
            DATABASE_JDBC_URL: "jdbc:postgresql://postgresql.{{ .Values.cluster.namespace }}.svc.cluster.local:5432/ejbca"
        nginx:
          host: *hostname 
  - repoURL: "https://code.europa.eu/api/v4/projects/{{ .Values.simpl_cloud_gateway.projectID }}/packages/helm/stable"
    path: ''
    targetRevision: {{ .Values.simpl_cloud_gateway.targetRevision }}
    chart: {{ .Values.simpl_cloud_gateway.chart_name }}
    helm:
      valueFiles:
        {{- range .Values.simpl_cloud_gateway.valueFiles }}
        - $values/app-values/Simpl-Cloud-Gateway/{{ . }}
        {{- end }}
      values: |
        microservices:
          usersRolesUrl: http://users-roles.{{ .Values.cluster.namespace }}.svc.cluster.local:8080
          securityAttributesProviderUrl: http://security-attributes-provider.{{ .Values.cluster.namespace }}.svc.cluster.local:8080
          keycloakUrl: http://keycloak.{{ .Values.cluster.namespace }}.svc.cluster.local
          onboardingUrl: http://onboarding.{{ .Values.cluster.namespace }}.svc.cluster.local:8080
          ejbcaUrl: http://ejbca-community-helm.{{ .Values.cluster.namespace }}.svc.cluster.local:30080
        global:
          hostBe: authority.be.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
          hostTls: tls.authority.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
          hostFe: authority.fe.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
          authorityUrl: https://authority.be.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
          keystore:
            password: "authority"
          cors:
            allowOrigin: https://authority.fe.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }},https://authority.fe.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }},http://localhost:4202,http://localhost:3000     
  - repoURL: "https://code.europa.eu/api/v4/projects/{{ .Values.simpl_fe.projectID }}/packages/helm/stable"
    path: "''"
    targetRevision: {{ .Values.simpl_fe.targetRevision }}
    chart: {{ .Values.simpl_fe.chart_name }}
    helm:
      valueFiles:
        {{- range .Values.simpl_fe.valueFiles }}
        - $values/app-values/Simpl-fe/{{ . }}
        {{- end }}
      values: |
        image:
          tag: {{ .Values.simpl_fe.targetRevision }}
        hostBe: authority.be.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
        hostFe: authority.fe.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
        cors:
          allowOrigin: https://authority.fe.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }},http://localhost:4202,http://localhost:4203,http://localhost:3000
        ingress:
          issuer: dev-prod
        env:
        - name: APPLICATION
          value: onboarding
        - name: API_URL
          value: "https://authority.be.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}"
        - name: KEYCLOAK_URL
          value: "https://authority.be.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}/auth"
        - name: KEYCLOAK_REALM
          value: "authority"
        - name: KEYCLOAK_CLIENT_ID
          value: "frontend-cli"
  - repoURL: "https://code.europa.eu/api/v4/projects/{{ .Values.sap.projectID }}/packages/helm/stable"
    path: ''
    targetRevision: {{ .Values.sap.targetRevision }}
    chart: {{ .Values.sap.chart_name }}
    helm:
      valueFiles:
        {{- range .Values.sap.valueFiles }}
        - $values/app-values/SAP/{{ . }}
        {{- end }}
      values: |
        global:
          hostTls: tls.authority.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
          keystore:
            password: "authority"
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql.{{ .Values.cluster.namespace }}.svc.cluster.local:5432/securityattributesprovider
          SPRING_DATA_REDIS_HOST: "redis-master.{{ .Values.cluster.namespace }}.svc.cluster.local"
          MICROSERVICE_USERS_ROLES_URL: http://users-roles.{{ .Values.cluster.namespace }}.svc.cluster.local:8080
          MICROSERVICE_ONBOARDING_URL: http://onboarding.{{ .Values.cluster.namespace }}.svc.cluster.local:8080
  - repoURL: "https://code.europa.eu/api/v4/projects/{{ .Values.users_roles.projectID }}/packages/helm/stable"
    path: ''
    targetRevision: {{ .Values.users_roles.targetRevision }}
    chart: {{ .Values.users_roles.chart_name }}
    helm:
      valueFiles:
        {{- range .Values.users_roles.valueFiles }}
        - $values/app-values/Users-Roles/{{ . }}
        {{- end }}
      values: |
        global:
          hostBe: authority.be.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
          hostTls: tls.authority.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
          hostFe: authority.fe.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
          authorityUrl: https://authority.be.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
          keystore:
            password: "authority"
          cors:
            allowOrigin: https://authority.fe.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }},http://localhost:4202,http://localhost:3000
        env:
          SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql.{{ .Values.cluster.namespace }}.svc.cluster.local:5432/usersroles"
          SPRING_DATA_REDIS_HOST: "redis-master.{{ .Values.cluster.namespace }}.svc.cluster.local"
  - repoURL: {{ .Values.redis.repo_URL }}
    targetRevision: {{ .Values.redis.targetRevision }}
    chart: {{ .Values.redis.chart_name }}
    helm:
      valueFiles:
        {{- range .Values.redis.valueFiles }}
        - $values/app-values/Redis/{{ . }}
        {{- end }}
      values: |
        fullnameOverride: {{ .Values.redis.fullnameOverride }}
  - repoURL: {{ .Values.xsfc_data_catalogue.repo_URL }}
    targetRevision: {{ .Values.xsfc_data_catalogue.branch }}
    path: {{ .Values.xsfc_data_catalogue.path }}
    helm:
      valueFiles:
        {{- range .Values.xsfc_data_catalogue.valueFiles }}
        - $values/app-values/xsfc-data-catalogue/{{ . }}
        {{- end }}
      values: |
        podSecurityContext: 
          allowPrivilegeEscalation: false
        ingress:
          hosts:
            - host: xsfc-data-server-service.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: xsfc-data-server-tls
              hosts:
                - xsfc-data-server-service.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
        hashicorp:
          service: {{ .Values.hashicorp.service }}
        secretEngine: {{ .Values.secretEngine }}
  - repoURL: {{ .Values.xsfc_infra_catalogue.repo_URL }}
    targetRevision: {{ .Values.xsfc_infra_catalogue.branch }}
    path: {{ .Values.xsfc_infra_catalogue.path }}
    helm:
      valueFiles:
        {{- range .Values.xsfc_infra_catalogue.valueFiles }}
        - $values/app-values/xsfc-infra-catalogue/{{ . }}
        {{- end }}
      values: |
        podSecurityContext: 
          allowPrivilegeEscalation: false
        ingress:
          hosts:
            - host: xsfc-infra-server-service.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: xsfc-infra-server-tls
              hosts:
                - xsfc-infra-server-service.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
        hashicorp:
          service: {{ .Values.hashicorp.service }}
        secretEngine: {{ .Values.secretEngine }}
  - repoURL: "https://code.europa.eu/api/v4/projects/{{ .Values.onboarding.projectID }}/packages/helm/stable"
    path: ''
    targetRevision: {{ .Values.onboarding.targetRevision }}
    chart: {{ .Values.onboarding.chart_name }}
    helm:
      valueFiles:
        {{- range .Values.onboarding.valueFiles }}
        - $values/app-values/onboarding/{{ . }}
        {{- end }}
      values: |
        global:
          hostTls: "https://onboarding.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}"
          keystore:
            password: "your-keystore-password"
        env:
          SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql.{{ .Values.cluster.namespace }}.svc.cluster.local:5432/onboarding"
        ejbca:
          enrollConfig:
            url: "https://ejbca-community-helm.{{ .Values.cluster.namespace }}.svc.cluster.local:30443"
          keystore:
            base64: {{ .Values.onboarding.keystore.base64 }}
            password: {{ .Values.onboarding.keystore.password }}
          truststore: 
            base64: {{ .Values.onboarding.truststore.base64 }}
            password: {{ .Values.onboarding.truststore.password }}
  - repoURL: "https://code.europa.eu/api/v4/projects/{{ .Values.tls_gateway.projectID }}/packages/helm/stable"
    path: ''
    targetRevision: {{ .Values.tls_gateway.targetRevision }}
    chart: {{ .Values.tls_gateway.chart_name }}
    helm:
      valueFiles:
        {{- range .Values.tls_gateway.valueFiles }}
        - $values/app-values/tls-gateway/{{ . }}
        {{- end }}
      values: |
        microservices:
          securityAttributesProviderUrl: http://security-attributes-provider.{{ .Values.cluster.namespace }}.svc.cluster.local:8080
        global:  
          cors:
            allowOrigin: https://authority.fe.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }},https://authority.be.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }},http://localhost:4202,http://localhost:3000
  - repoURL: "https://code.europa.eu/api/v4/projects/{{ .Values.poc_gaia_edc.projectID }}/packages/helm/stable"
    path: ''
    targetRevision: {{ .Values.poc_gaia_edc.targetRevision }}
    chart: {{ .Values.poc_gaia_edc.chart_name }}
    helm:
      releaseName: {{ .Values.poc_gaia_edc.fullnameOverride }}
      valueFiles:
        {{- range .Values.poc_gaia_edc.valueFiles }}
        - $values/app-values/poc-gaia-edc/{{ . }}
        {{- end }}
      values: |
        podSecurityContext: 
          allowPrivilegeEscalation: false
        ingress:
          host: adapter.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
          tls:
            secretName: adapter-simpl-backend-tls
        secretEngine: {{ .Values.secretEngine }}