apiVersion: v1
kind: ConfigMap
metadata:
  name: import-ttl-job
data:
  import-ttl.sh: |
    #!/bin/bash

    # Exit on error
    set -e

    # Usage check
    if [ -z "$1" ]; then
      echo "Usage: $0 <ENDPOINT_URL>"
      exit 1
    fi

    # Get the endpoint from the first argument
    ENDPOINT_URL="$1"
    SCHEMA_PATH="/schemas"

    # Healthcheck
    until curl -s --head --fail "$1/schemas" >/dev/null; do echo "Waiting for endpoint to become available..."; sleep 5; done

    # Raw file URLs
    FILE1_URL="https://code.europa.eu/simpl/simpl-open/development/data1/sdtooling-sd-schemas/-/raw/main/yaml2ontology/simpl_ontology_generated.ttl"
    FILE2_URL="https://code.europa.eu/simpl/simpl-open/development/data1/sdtooling-sd-schemas/-/raw/main/yaml2shape/merged-shapes.ttl"

    # Temporary files
    TMP1=$(mktemp)
    TMP2=$(mktemp)

    # Download the files
    curl -sSL "$FILE1_URL" -o "$TMP1"
    curl -sSL "$FILE2_URL" -o "$TMP2"

    # POST the first file
    curl --location "${ENDPOINT_URL}${SCHEMA_PATH}" \
      --header "Content-Type: text/turtle" \
      --header "Accept: application/json" \
      --data-binary @"$TMP1"

    # POST the second file
    curl --location "${ENDPOINT_URL}${SCHEMA_PATH}" \
      --header "Content-Type: text/turtle" \
      --header "Accept: application/json" \
      --data-binary @"$TMP2"

    # Clean up
    rm "$TMP1" "$TMP2"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: import-ttl-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  backoffLimit: 12
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      containers:
      - name: script-runner
        image: quay.io/curl/curl
        command: ["/bin/sh", "/postconfig/import-ttl.sh", "https://xsfc-server-service.{{ .Values.namespaceTag.authority }}.{{ .Values.domainSuffix }}"]
        volumeMounts:
        - name: postconfig-volume
          mountPath: /postconfig
      volumes:
      - name: postconfig-volume
        configMap:
          name: import-ttl-job