global:
  profile: authority
  ingress:
    issuer: { { .Values.certificateIssuer } }

  hostBe: "{{ .Values.t1hostname }}.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}"
  hostTls: tls.authority.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
  hostFe: authority.fe.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
  authorityUrl: https://authority.be.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }}
  keystore:
    password: "authority"
  cors:
    allowOrigin: https://authority.fe.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }},https://authority.fe.{{ .Values.namespaceTag }}.{{ .Values.domainSuffix }},http://localhost:4202,http://localhost:3000

microservices:
  usersRolesUrl: http://users-roles.{{ .Values.cluster.namespace }}.svc.cluster.local:8080
  securityAttributesProviderUrl: http://security-attributes-provider.{{ .Values.cluster.namespace }}.svc.cluster.local:8080
  keycloakUrl: http://keycloak.{{ .Values.cluster.namespace }}.svc.cluster.local
  onboardingUrl: http://onboarding.{{ .Values.cluster.namespace }}.svc.cluster.local:8080
  ejbcaUrl: http://ejbca-community-helm.{{ .Values.cluster.namespace }}.svc.cluster.local:30080
