SERVICE_PORT: 8084
CONTAINER_PORT: 8084
DEPLOYMENT_IMAGE_PULL_POLICY: Always

secretConfigPath: "{{ .Values.hashicorp.secretEngine }}/{{ .Release.Namespace }}-adapter-simpl-backend"

deployment:
  label: poc

serviceAccount:
  enabled: true
  name: "adapter-sa"

podSecurityContext: 
  allowPrivilegeEscalation: false

ingress:
  tls:
    secretName: adapter-simpl-backend-tls