serviceAccount:
  name: "ejbca-svc-account"

appConfig:
  ejbca:
    url: "https://ejbca-community-helm:30443"
  spring:
    ssl:
      bundle:
        jks:
          ejbca:
            key:
              alias: "superadmin"
            keystore:
              password: "vault:{{ .Values.hashicorp.secretEngine }}/data/{{ .Values.cluster.namespace }}-ejbca#keystorepass"
            truststore:
              password: "changeit"

  microservice:
    security-attributes-provider:
      url: "http://security-attributes-provider:8080"

  ejbca:
    url: "https://ejbca-community-helm:30443"
    profile-name: "Onboarding TLS Profile"
    end-entity-name: "Onboarding End Entity"
    ca-name: "OnBoardingCA"

  simpl:
    authority-participant-type-placeholder: GOVERNANCE_AUTHORITY