project: ${PROJECT}
namespaceTag: ${NAMESPACETAG}
domainSuffix: ${DOMAINSUFFIX}

argocd:
  appname: ${NAMESPACE}
  namespace: argocd

cluster:
  address: https://kubernetes.default.svc
  namespace: ${NAMESPACE}

values:
  repo_URL: https://code.europa.eu/simpl/simpl-open/development/agents/governance-authority.git
  branch: develop

postgresql:
  repo_URL: https://charts.bitnami.com/bitnami
  chart_name: postgresql
  targetRevision: 15.2.5
  fullnameOverride: postgresql
  valueFiles:
    - values.yaml
    - values-authority.yaml

keycloak:
  repo_URL: https://charts.bitnami.com/bitnami
  chart_name: keycloak
  targetRevision: "21.2.2"
  fullnameOverride: keycloak
  valueFiles:
    - values.yaml

redis:
  repo_URL: 'https://charts.bitnami.com/bitnami'
  targetRevision: 19.6.0
  chart_name: redis
  fullnameOverride: redis
  valueFiles:
    - values.yaml

simpl_cloud_gateway:
  projectID: "772"
  targetRevision: 0.0.4
  chart_name: simpl-cloud-gateway
  valueFiles:
    - values.yaml
    - values-authority.yaml

simpl_fe:
  projectID: "769"
  targetRevision: 0.0.4-620.hotfix.48569299
  chart_name: simpl-fe
  valueFiles:
    - values.yaml
    - values-authority.yaml

sap:
  projectID: "861"
  targetRevision: 0.0.4
  chart_name: security-attributes-provider
  valueFiles:
    - values.yaml

users_roles:
  projectID: "771"
  targetRevision: 0.0.41-591.hotfix.b1dfc6f7
  chart_name: users-roles
  valueFiles:
    - values.yaml
    
xsfc_data_catalogue:
  repo_URL: 'https://code.europa.eu/simpl/simpl-open/development/gaia-x-edc/simpl-fc-service.git'
  branch: main
  #targetRevision: 0.1.4
  chart_name: data-catalogue-fc-service
  path: "deployment/helm/fc-service"
  valueFiles:
    - values.yaml
    
xsfc_infra_catalogue:
  repo_URL: 'https://code.europa.eu/simpl/simpl-open/development/gaia-x-edc/simpl-fc-service.git'
  branch: main
  #targetRevision: 0.1.4
  chart_name: data-catalogue-fc-service
  path: "deployment/helm/fc-service"
  valueFiles:
    - values.yaml

ejbca:
  repo_URL: https://code.europa.eu/simpl/simpl-open/development/iaa/charts.git
  branch: feature/integration-refactor
  folder: ejbca-community-helm
  fullnameOverride: ejbca-community-helm
  valueFiles:
    - values.yaml
    - values-authority.yaml

onboarding:
  projectID: "770"
  targetRevision: 0.0.5-256.hotfix.219d6217
  chart_name: onboarding
  valueFiles:
    - values.yaml

poc_gaia_edc:
  projectID: "759"
  targetRevision: 0.1.7
  chart_name: poc-charts
  fullnameOverride: catalogue
  valueFiles:
    - values.yaml

tls_gateway:
  projectID: "860"
  targetRevision: 0.0.5-106.hotfix.9753e494
  chart_name: tls-gateway
  valueFiles:
    - values.yaml