springRoutes:
  - id: sap
    uri: ${sap.url}
    predicates:
      - Path=/sap-api/mtls/**
    filters:
      - StripPrefix=1
  - id: identity-provider
    uri: ${identity-provider.url}
    predicates:
      - Path=/identity-api/mtls/**
    filters:
      - StripPrefix=1
  - id: users-roles
    uri: ${users-roles.url}
    predicates:
      - Path=/user-api/mtls/**
    filters:
      - StripPrefix=1
routes:
  publicUrls:
    - method: GET
      path: "/actuator/**"

  abac:
    - method: PATCH
      path: "/identity-api/mtls/public-key"
      disableEphemeralProofCheck: true
    - method: POST
      path: "/identity-api/mtls/token"
      disableEphemeralProofCheck: true
    - method: POST
      path: "/user-api/mtls/ephemeral-proof"
      disableEphemeralProofCheck: true
