appConfig:
  spring:
    cloud:
      gateway:
        routes:
          - id: sap
            uri: ${sap.url}
            predicates:
              - Path=/sap-api/mtls/**
            filters:
              - StripPrefix=1
          - id: identity-provider
            uri: ${identity-provider.url}
            predicates:
              - Path=/identity-api/mtls/**
            filters:
              - StripPrefix=1
          - id: users-roles
            uri: ${users-roles.url}
            predicates:
              - Path=/user-api/mtls/**
            filters:
              - StripPrefix=1
          - id: fc-service
            uri: "https://xfsc-service.{{ .Values.cluster.namespace }}.svc.cluster.local:8081"
            predicates:
              - Path=/fc/**
            filters:
              - StripPrefix=1
          - id: adapter-service
            uri: "https://adapter.{{ .Values.cluster.namespace }}.svc.cluster.local:8084"
            predicates:
              - Path=/adapter/**
            filters:
              - StripPrefix=1
  routes:
    public-urls:
      - method: GET
        path: "/actuator/**"
      - method: GET
        path: "/fc/**"
      - method: POST
        path: "/fc/**"
      - method: PUT
        path: "/fc/**"
      - method: DELETE
        path: "/fc/**"
      - method: POST
        path: "/adapter/**"
      - method: GET
        path: "/adapter/**"

    abac:
      - method: PATCH
        path: "/identity-api/mtls/public-key"
        disable-ephemeral-proof-check: true
      - method: POST
        path: "/identity-api/mtls/token"
        disable-ephemeral-proof-check: true
      - method: POST
        path: "/user-api/mtls/ephemeral-proof"
        disable-ephemeral-proof-check: true
