appConfig:
  spring:
    cloud:
      gateway:
        routes:
          - id: sap
            uri: ${sap.url}
            predicates:
              - Path=/sap-api/mtls/**
            filters:
              - StripPrefix=1
          - id: identity-provider
            uri: ${identity-provider.url}
            predicates:
              - Path=/identity-api/mtls/**
            filters:
              - StripPrefix=1
          - id: users-roles
            uri: ${users-roles.url}
            predicates:
              - Path=/user-api/mtls/**
            filters:
              - StripPrefix=1
  routes:
    public-urls:
      - method: GET
        path: "/actuator/**"

    abac:
      - method: PATCH
        path: "/identity-api/mtls/public-key"
        disable-ephemeral-proof-check: true
      - method: POST
        path: "/identity-api/mtls/token"
        disable-ephemeral-proof-check: true
      - method: POST
        path: "/user-api/mtls/ephemeral-proof"
        disable-ephemeral-proof-check: true

    logging:
      business:
        - method: GET
          path: /some/path/*
          config:
            message: Businesslogsmessage
            operations:
              - OP1
              - OP2
