appConfig:
  spring:
    cloud:
      gateway:
        routes:
          - id: sap
            uri: ${sap.url}
            predicates:
              - Path=/sap-api/mtls/**
            filters:
              - StripPrefix=1
          - id: identity-provider
            uri: ${identity-provider.url}
            predicates:
              - Path=/identity-api/mtls/**
            filters:
              - StripPrefix=1
          - id: users-roles
            uri: ${users-roles.url}
            predicates:
              - Path=/user-api/mtls/**
            filters:
              - StripPrefix=1
  routes:
    public-urls:
      - method: GET
        path: "/actuator/**"

    abac:
      - method: PATCH
        path: "/identity-api/mtls/public-key"
        disable-ephemeral-proof-check: true
      - method: POST
        path: "/identity-api/mtls/token"
        disable-ephemeral-proof-check: true
      - method: POST
        path: "/user-api/mtls/ephemeral-proof"
        disable-ephemeral-proof-check: true
    
    rbac:
      - method: GET
        path: "/fc/**"
        disable-ephemeral-proof-check: true
      - method: POST
        path: "/fc/**"
        disable-ephemeral-proof-check: true
      - method: PUT
        path: "/fc/**"
        disable-ephemeral-proof-check: true
      - method: DELETE
        path: "/fc/**"
        disable-ephemeral-proof-check: true
      - method: POST
        path: "/adapter/**"
        disable-ephemeral-proof-check: true
      - method: GET
        path: "/adapter/**"
        disable-ephemeral-proof-check: true

    logging:
      business:
      - config:
          operations:
          - PING_REQUEST
        method: GET
        path: /user-api/mtls/ping
      - config:
          operations:
          - ECHO_REQUEST
        method: GET
        path: /identity-api/mtls/echo
      - config:
          operations:
          - PUBLISH_CATALOG
        method: POST
        path: /fc/self-descriptions/*
      - config:
          operations:
          - PUBLISH_CATALOG
        method: POST
        path: /fc/self-descriptions
      - config:
          operations:
          - SEARCH_CATALOG
        method: POST
        path: /adapter/api/v1/search/*