global:
  profile: authority

autoscaling:
  enabled: false

keycloak:
  master:
    user: "admin"
    realm: "authority"
  clientToRealmRoleMigration:
    enabled: true # set to true to import realm roles from client roles
    clientIds: "['frontend-cli']"

databaseSeeding:
  roleIdentityAttributesMapping:
    # If you want to start with an empty identity attributes table, set this to false.
    # Ff enabled is set to true and filePath is commented or empty the table will be initialized with the default seeding file.
    enabled: true 
