auth:
  adminUser: "admin"
  adminPassword: "admin"

postgresql:
  enabled: false

externalDatabase:
  annotations: {}
  database: keycloak
  existingSecret: ""
  existingSecretDatabaseKey: ""
  existingSecretHostKey: ""
  existingSecretPasswordKey: ""
  existingSecretPortKey: ""
  existingSecretUserKey: ""
  password: keycloak
  port: 5432
  user: keycloak

extraVolumes:
  - name: spi-volume
    emptyDir: {}
  - name: realm-volume
    emptyDir: {}

extraVolumeMounts:
  - name: spi-volume
    mountPath: /opt/bitnami/keycloak/providers/keycloak-authenticator.jar
    subPath: keycloak-authenticator.jar
  - name: realm-volume
    mountPath: /opt/bitnami/keycloak/data/import/realm.json
    subPath: realm.json

initContainers: 
  - name: init-spi
    image: curlimages/curl
    command: ["/bin/sh", "-c"]
    env:
      - name: ARTIFACT
        value: keycloak-authenticator
      - name: URL
        value: https://code.europa.eu/api/v4/projects/915/packages/maven/com/aruba/simpl/keycloak-authenticator/0.7.1/keycloak-authenticator-0.7.1.jar
    args:
      - |
        curl -o /custom-spi/${ARTIFACT}.jar ${URL};
    volumeMounts:
      - name: spi-volume
        mountPath: /custom-spi

  - name: import-realm
    image: curlimages/curl
    command: ["/bin/sh", "-c"]
    env:
      - name: REALM_NAME
        value: realm
      - name: URL
        # uncomment below if you are deploying an authority
        # value: https://code.europa.eu/simpl/simpl-open/development/iaa/charts/-/raw/develop/samples/keycloak-realms/0.7.1/authority-realm-export.json?ref_type=heads
        # uncomment below if you are deploying an authority (realm with federated-catalogue client)
        value: https://code.europa.eu/simpl/simpl-open/development/agents/governance-authority/-/raw/feature/SIMPL-7561/app-values/Keycloak/0.4.x/realm-export.json         
        # uncomment below if you are deploying a participant
        # value: https://code.europa.eu/simpl/simpl-open/development/iaa/charts/-/raw/develop/samples/keycloak-realms/0.7.1/participant-realm-export.json?ref_type=heads
    args:
      - |
        curl -o /config/${REALM_NAME}.json ${URL};
    volumeMounts:
      - name: realm-volume
        mountPath: /config
