securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001

envFrom:
  - configMapRef:
      name: simpl-cli-configmap

initAuthority:
  enabled: true
  csr:
    country: EU
  ejbca:
    internalPort: 30443
  keycloak:
    internalPort: 80
    app:
      realm: authority
      clientId: cli
    master:
      realm: master
      user: admin
      clientId: admin-cli
initParticipant:
  enabled: false